### ISSUE TITLE
Not able to proxy to Ingress URL via Spring Cloud Gateway

### ISSUE THREAD

**Issue by MeiJiawei** [dandamudi1414/findme#1]
https://github.com/spring-cloud/spring-cloud-gateway/issues/1936
I also ,How did you deal with this problem? thx

**Comment by dandamudi1414** [comment]
@MeiJiawei  - Are you getting the same below error in the target containers ?? Which version of Spring cloud gateway?

java.lang.IllegalArgumentException: The character [,] is never valid in a domain name.
gateway-dev.lab.example.net,gateway-dev.lab.example.net

**Comment by MeiJiawei** [comment]
> @MeiJiawei - Are you getting the same below error in the target containers ?? Which version of Spring cloud gateway?
> 
> java.lang.IllegalArgumentException: The character [,] is never valid in a domain name.
> gateway-dev.lab.example.net,gateway-dev.lab.example.net

yes,  spring cloud version <spring.cloud.version>Hoxton.SR8</spring.cloud.version> 

at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [na:1.8.0_144]
	at org.apache.tomcat.util.http.parser.Host.parse(Host.java:45) ~[tomcat-embed-core-9.0.37.jar!/:9.0.37]
	at org.apache.tomcat.util.http.parser.HttpParser$DomainParseState.next(HttpParser.java:974) ~[tomcat-embed-core-9.0.37.jar!/:9.0.37]
java.lang.IllegalArgumentException: The character [,] is never valid in a domain name.
	at org.apache.tomcat.util.http.parser.Host.parse(Host.java:71) ~[tomcat-embed-core-9.0.37.jar!/:9.0.37]

**Comment by dandamudi1414** [comment]
we are assuming an issue with nginix  / tomcat version ...  for us workaround was to use the **internal service URL** instead of the **ingress URL**   like **http://app.<namespace>/contextpath/**
